# Import Necessary Libraries

In [1]:
import pandas as pd 
import numpy as np
import plotly.express as px
import seaborn as sns

# Reading DataSet

In [4]:
df = pd.read_excel("Crust & Crumb Bakery(1).xlsx")
df

,Date,Time of Day,Revenue,Ad Spend,Conversions,Season,Channel,Service Type,Customer Type
0,2025-02-26,Afternoon,377.54,1.63,2,Winter,Referral,Basic,New
1,2024-12-03,Morning,347.75,43.98,5,Winter,Google Ads,Basic,New
2,2024-08-03,Evening,412.00,27.41,4,Summer,Google Ads,Premium,Returning
3,2024-05-15,Morning,295.78,3.90,5,Spring,Facebook,Basic,Returning
4,2025-03-25,Afternoon,178.34,44.21,10,Spring,Walk-in,Package,Returning
...,...,...,...,...,...,...,...,...,...
1995,2024-12-03,Evening,386.08,37.23,2,Winter,Google Ads,Premium,Returning
1996,2024-11-11,Morning,423.86,25.22,10,Fall,Facebook,Premium,Returning
1997,2024-12-25,Afternoon,127.69,5.07,5,Winter,Facebook,Premium,New
1998,2024-12-10,Morning,336.53,16.79,2,Winter,Instagram,Basic,New
1999,2025-01-23,Afternoon,86.96,32.04,8,Winter,Walk-in,Premium,New

# Data Exploration

## Check data type for columns

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           2000 non-null   datetime64[ns]
 1   Time of Day    2000 non-null   object
 2   Revenue        2000 non-null   float64
 3   Ad Spend       2000 non-null   float64
 4   Conversions    2000 non-null   int64
 5   Season         2000 non-null   object
 6   Channel        2000 non-null   object
 7   Service Type   2000 non-null   object
 8   Customer Type  2000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 140.8+ KB

## Show Sample of DataSet

In [8]:
df.head()

,Date,Time of Day,Revenue,Ad Spend,Conversions,Season,Channel,Service Type,Customer Type
0,2025-02-26,Afternoon,377.54,1.63,2,Winter,Referral,Basic,New
1,2024-12-03,Morning,347.75,43.98,5,Winter,Google Ads,Basic,New
2,2024-08-03,Evening,412.00,27.41,4,Summer,Google Ads,Premium,Returning
3,2024-05-15,Morning,295.78,3.90,5,Spring,Facebook,Basic,Returning
4,2025-03-25,Afternoon,178.34,44.21,10,Spring,Walk-in,Package,Returning

In [9]:
df.tail()

,Date,Time of Day,Revenue,Ad Spend,Conversions,Season,Channel,Service Type,Customer Type
1995,2024-12-03,Evening,386.08,37.23,2,Winter,Google Ads,Premium,Returning
1996,2024-11-11,Morning,423.86,25.22,10,Fall,Facebook,Premium,Returning
1997,2024-12-25,Afternoon,127.69,5.07,5,Winter,Facebook,Premium,New
1998,2024-12-10,Morning,336.53,16.79,2,Winter,Instagram,Basic,New
1999,2025-01-23,Afternoon,86.96,32.04,8,Winter,Walk-in,Premium,New

## Check Missing Values

In [10]:
df.isna().sum()

Date             0
Time of Day      0
Revenue          0
Ad Spend         0
Conversions      0
Season           0
Channel          0
Service Type     0
Customer Type    0
dtype: int64

## Check Duplicates

In [11]:
df.duplicated().sum()

np.int64(0)

## Checking Columns in depth

### Checking Categorical Columns in depth

In [12]:
cat_cols=df.select_dtypes(include="object").columns
cat_cols

Index(['Time of Day', 'Season', 'Channel', 'Service Type', 'Customer Type'], dtype='object')

In [13]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print("-"*100)

Time of Day
4
['Afternoon' 'Morning' 'Evening' 'Night']
----------------------------------------------------------------------------------------------------
Season
4
['Winter' 'Summer' 'Spring' 'Fall']
----------------------------------------------------------------------------------------------------
Channel
5
['Referral' 'Google Ads' 'Facebook' 'Walk-in' 'Instagram']
----------------------------------------------------------------------------------------------------
Service Type
3
['Basic' 'Premium' 'Package']
----------------------------------------------------------------------------------------------------
Customer Type
2
['New' 'Returning']
----------------------------------------------------------------------------------------------------

### Check Numerical Columns in depth

In [14]:
num_cols=df.select_dtypes(include="number").columns
num_cols

Index(['Revenue', 'Ad Spend', 'Conversions'], dtype='object')

In [15]:
for col in num_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print("-"*100)

Revenue
1963
[377.54 347.75 412.   ... 423.86 336.53  86.96]
----------------------------------------------------------------------------------------------------
Ad Spend
1646
[ 1.63 43.98 27.41 ... 25.22 16.79 32.04]
----------------------------------------------------------------------------------------------------
Conversions
11
[ 2  5  4 10  7  0  6  9  3  1  8]
----------------------------------------------------------------------------------------------------

In [16]:
for col in num_cols:
    px.histogram(df, x=col, title=f"Distribution of {col}").show()